import { ContactInfo, SocialMedia, Stat, Program, Coach, Facility, Swimmer, Event } from '../types';

export const CONTACT_INFO: ContactInfo = {
  phone: '+256 709 711 797',
  email: 'silverfinacademy@gmail.com',
  address: 'Hill Preparatory School, Naguru, Kampala'
};

export const SOCIAL_MEDIA: SocialMedia = {
  instagram: 'https://instagram.com/silverfinacademy',
  facebook: 'https://facebook.com/silverfinacademy',
  youtube: 'https://youtube.com/silverfinacademy'
};

export const CLUB_STATS: Stat[] = [
  { value: '150+', label: 'Active Members' },
  { value: '92', label: 'Medals Won' },
  { value: '14', label: 'Coaches & Staff' },
  { value: '6', label: 'Training Squads' }
];

export const PROGRAMS: Program[] = [
  {
    id: 'learn-to-swim',
    title: 'Learn to Swim',
    description: 'Water confidence, safety, and foundational technique for beginners.',
    meta: 'Ages 4–10 • Weekdays',
    ageGroup: '4-10',
    duration: '4 weeks'
  },
  {
    id: 'development-squads',
    title: 'Development Squads',
    description: 'Skill refinement and aerobic base with fun, progressive sets.',
    meta: 'Ages 9–14 • 4–6 sessions/week',
    ageGroup: '9-14',
    duration: 'Monthly'
  },
  {
    id: 'performance-senior',
    title: 'Performance / Senior',
    description: 'High‑performance training targeting national and international meets.',
    meta: 'Ages 13+ • 7–9 sessions/week',
    ageGroup: '13+',
    duration: 'Monthly'
  }
];

export const COACHES: Coach[] = [
  {
    id: 'ezra-kakali',
    name: 'Ezra Kakali',
    title: 'Head Coach',
    imageUrl: '/logo/logo.jpg',
    bio: 'Former national team swimmer with 15+ years coaching experience leading Silverfin to regional excellence. Ezra represented Uganda at the Commonwealth Games and African Championships before transitioning to coaching. His technical expertise and leadership have transformed countless swimmers into champions.',
    quote: "Excellence is not a destination, it's a journey. Every stroke, every training session, every competition is an opportunity to become better than you were yesterday.",
    background: 'Swimming Career: Competed internationally for Uganda (2005-2012)\nCoaching Experience: 15+ years developing athletes from beginner to elite level\nEducation: Sports Science degree, University of Makerere\nAchievements: Led 50+ swimmers to national championships, developed 12 African Championship medalists',
    certifications: [
      'Level 4 Swimming Coach (Swimming Federation)',
      'Strength & Conditioning Specialist (NSCA)',
      'Water Safety Instructor (Red Cross)',
      'Mental Performance Coach',
      'Technical Official Level 3',
      'First Aid/CPR Certified'
    ]
  },
  {
    id: 'vincent-kabira',
    name: 'Vincent Kabira',
    title: 'Assistant Head Coach',
    imageUrl: '/logo/logo.jpg',
    bio: 'Specialist in competitive swimming development with expertise in stroke technique and race strategy. Vincent focuses on developing proper fundamentals and building competitive confidence in swimmers of all levels.',
    quote: "Technique is the foundation of speed. Perfect practice makes perfect performance, and every swimmer has the potential to achieve greatness with the right guidance.",
    background: 'Swimming Career: Former national age-group record holder\nCoaching Experience: 8+ years specializing in technique development\nEducation: Physical Education degree, Kyambogo University\nSpecialization: Stroke biomechanics and race preparation',
    certifications: [
      'Level 3 Swimming Coach',
      'Technical Official Level 2',
      'Child Protection Certified',
      'Video Analysis Specialist',
      'Age Group Development Coach',
      'First Aid/CPR Certified'
    ]
  },
  {
    id: 'mugisha-jacob',
    name: 'Mugisha Jacob',
    title: 'Learn to Swim Coach (Adults)',
    imageUrl: '/logo/logo.jpg',
    bio: 'Dedicated adult swimming instructor with a passion for helping beginners overcome water fears and develop confidence in the water. Jacob specializes in working with adult learners who are taking up swimming later in life.',
    background: 'Teaching Experience: 6+ years specializing in adult education\nEducation: Certificate in Adult Education, YMCA\nSpecialization: Water confidence and fear management\nSuccess Rate: 95% of students achieve basic swimming competency',
    certifications: [
      'Adult Swimming Instructor (Level 2)',
      'Water Safety Instructor',
      'First Aid/CPR Certified',
      'Aquatic Therapy Assistant',
      'Adult Education Certificate'
    ]
  },
  {
    id: 'nancy-akukwatswe',
    name: 'Nancy Akukwatswe',
    title: 'Learn to Swim Coach (Children)',
    imageUrl: '/logo/logo.jpg',
    bio: 'Patient and encouraging instructor specializing in foundational swimming skills for children aged 4-12. Nancy creates a fun, safe environment where young swimmers can develop both skills and confidence.',
    background: 'Teaching Experience: 7+ years in pediatric aquatic education\nEducation: Early Childhood Development Certificate\nSpecialization: Child psychology and motor skill development\nAchievements: Taught over 500 children to swim safely',
    certifications: [
      'Swimming Instructor Level 2 (Children)',
      'Child Development Specialist',
      'Water Confidence Instructor',
      'Pediatric First Aid/CPR',
      'Safeguarding Children Certificate'
    ]
  },
];

export const FACILITIES: Facility[] = [
  {
    name: '8‑lane 25m pool',
    description: 'Olympic standard training pool with electronic timing',
    features: ['Electronic timing', 'Lane ropes', 'Starting blocks']
  },
  {
    name: 'Strength & Conditioning space',
    description: 'Fully equipped gym for dryland training',
    features: ['Free weights', 'Resistance machines', 'Plyometric equipment']
  },
  {
    name: 'Video analysis',
    description: 'State-of-the-art stroke analysis technology',
    features: ['Underwater cameras', 'Motion analysis software', 'Tablet review stations']
  }
];

export const NAV_ITEMS = [
  { id: 'about', label: 'About' },
  { id: 'stats', label: 'Statistics' },
  { id: 'programs', label: 'Programs' },
  { id: 'news', label: 'News' },
  { id: 'gallery', label: 'Gallery' },
  { id: 'contact', label: 'Contact' }
];

export const SWIMMERS: Swimmer[] = [
  // Learn to Swim Squad
  {
    id: 'jeremiah-bwogi-kisawuzi',
    name: 'Jeremiah Bwogi Kisawuzi',
    age: 4,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'rebecca-namiiro',
    name: 'Rebecca Namiiro',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'israel-kanyike',
    name: 'Israel Kanyike',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [
        { event: '25m Freestyle', time: '43.01S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'gabriel-mwesigwa-james-marie',
    name: 'Gabriel Mwesigwa James-Marie',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [
        { event: '25m Freestyle', time: '41.28S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'jonatha-bwogi-nabukeera',
    name: 'Jonatha Bwogi Nabukeera',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'aimie-imora',
    name: 'Aimie Imora',
    age: 6,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'christian-okecho-owori',
    name: 'Christian Okecho Owori',
    age: 6,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [
        { event: '25m Freestyle', time: '29.76S', date: '2024-01-15' },
        { event: '25m Backstroke', time: '30.53S', date: '2024-01-15' },
        { event: '25m Breaststroke', time: '38.91S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'roman-byaruhanga-emanzi',
    name: 'Roman Byaruhanga Emanzi',
    age: 6,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [
        { event: '25m Freestyle', time: '24.39S', date: '2024-01-15' },
        { event: '25m Backstroke', time: '31.66S', date: '2024-01-15' },
        { event: '25m Breaststroke', time: '37.72S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kimuli-enzo-israel',
    name: 'Kimuli Enzo Israel',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [
        { event: '25m Freestyle', time: '25.42S', date: '2024-01-15' },
        { event: '25m Backstroke', time: '31.08S', date: '2024-01-15' },
        { event: '25m Breaststroke', time: '1:06.13S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kwikiriza-wilma',
    name: 'Kwikiriza Wilma',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'lucas-mugisha',
    name: 'Lucas Mugisha',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [
        { event: '25m Freestyle', time: '21.35S', date: '2024-01-15' },
        { event: '25m Backstroke', time: '28.23S', date: '2024-01-15' },
        { event: '25m Breaststroke', time: '36.38S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'dorothy-nakazi',
    name: 'Dorothy Nakazi',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kisakye-mugwanya-gabriella-shalom',
    name: 'Kisakye Mugwanya Gabriella Shalom',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'abisha-abowe',
    name: 'Abisha Abowe',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/logo/logo.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },

  // Development Squad
  {
    id: 'nkoola-janine-jolie',
    name: 'Nkoola Janine Jolie',
    age: 8,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '26.89S', date: '2024-01-15' },
        { event: '25m Backstroke', time: '35.22S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/nkoolajaninejolie',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'lionel-abitegeka-edwards',
    name: 'Lionel Abitegeka Edwards',
    age: 8,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/lionelabitegekaedwards',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'tendo-matthew-ssaka',
    name: 'Tendo Matthew Ssaka',
    age: 8,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '16.94S', date: '2024-01-15' },
        { event: '50m Freestyle', time: '37.47S', date: '2024-01-15' },
        { event: '100m Freestyle', time: '1:25.36S', date: '2024-01-15' },
        { event: '25m Backstroke', time: '20.32S', date: '2024-01-15' },
        { event: '50m Backstroke', time: '44.82S', date: '2024-01-15' },
        { event: '100m Backstroke', time: '1:40.54S', date: '2024-01-15' },
        { event: '25m Breaststroke', time: '24.76S', date: '2024-01-15' },
        { event: '50m Breaststroke', time: '55.52S', date: '2024-01-15' },
        { event: '100m Breaststroke', time: '2:05.43S', date: '2024-01-15' },
        { event: '25m Butterfly', time: '19.69S', date: '2024-01-15' },
        { event: '50m Butterfly', time: '43.29S', date: '2024-01-15' },
        { event: '100m Butterfly', time: '1:48.97S', date: '2024-01-15' },
        { event: '100m IM', time: '1:49.05S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/tendomatthewssaka',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kanyike-kirabo-elnathan',
    name: 'Kanyike Kirabo Elnathan',
    age: 8,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '21.13S', date: '2024-01-15' },
        { event: '25m Backstroke', time: '25.63S', date: '2024-01-15' },
        { event: '50m Backstroke', time: '1:02.15S', date: '2024-01-15' },
        { event: '25m Breaststroke', time: '33.46S', date: '2024-01-15' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/kanyikekiraboelnathan',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'bena-nkundwa-ahumuza',
    name: 'Bena Nkundwa Ahumuza',
    age: 8,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/benankundwaahumuza',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elsa-victory-dande',
    name: 'Elsa Victory Dande',
    age: 9,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elsavictorydande',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'gianna-mary-musiimenta',
    name: 'Gianna Mary Musiimenta',
    age: 9,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '19.29S', date: '2024-03-15' },
        { event: '50m Freestyle', time: '34.89S', date: '2024-03-15' },
        { event: '100m Freestyle', time: '1:39.40S', date: '2024-03-15' },
        { event: '25m Backstroke', time: '23.54S', date: '2024-03-15' },
        { event: '50m Backstroke', time: '51.20S', date: '2024-03-15' },
        { event: '100m Backstroke', time: '1:56.87S', date: '2024-03-15' },
        { event: '25m Breaststroke', time: '28.17S', date: '2024-03-15' },
        { event: '50m Breaststroke', time: '1:03.48S', date: '2024-03-15' },
        { event: '100m Breaststroke', time: '2:17.23S', date: '2024-03-15' },
        { event: '25m Butterfly', time: '23.00S', date: '2024-03-15' },
        { event: '50m Butterfly', time: '55.39S', date: '2024-03-15' },
        { event: '100m IM', time: '1:59.18S', date: '2024-03-15' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/giannamarymusiimenta',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'diarah-sama',
    name: 'Diarah Sama',
    age: 10,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '15.53S', date: '2024-04-20' },
        { event: '50m Freestyle', time: '36.19S', date: '2024-04-20' },
        { event: '100m Freestyle', time: '1:26.20S', date: '2024-04-20' },
        { event: '25m Backstroke', time: '20.48S', date: '2024-04-20' },
        { event: '50m Backstroke', time: '45.31S', date: '2024-04-20' },
        { event: '100m Backstroke', time: '1:39.79S', date: '2024-04-20' },
        { event: '25m Breaststroke', time: '21.29S', date: '2024-04-20' },
        { event: '50m Breaststroke', time: '45.96S', date: '2024-04-20' },
        { event: '100m Breaststroke', time: '1:49.20S', date: '2024-04-20' },
        { event: '25m Butterfly', time: '17.98S', date: '2024-04-20' },
        { event: '50m Butterfly', time: '37.44S', date: '2024-04-20' },
        { event: '100m Butterfly', time: '1:37.45S', date: '2024-04-20' },
        { event: '100m IM', time: '1:31.57S', date: '2024-04-20' },
        { event: '200m IM', time: '3:30.45S', date: '2024-04-20' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/diarahsama',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'ivancka-ssaka',
    name: 'Ivancka Ssaka',
    age: 10,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '15.90S', date: '2024-05-10' },
        { event: '50m Freestyle', time: '31.54S', date: '2024-05-10' },
        { event: '100m Freestyle', time: '1:14.35S', date: '2024-05-10' },
        { event: '200m Freestyle', time: '2:54.32S', date: '2024-05-10' },
        { event: '400m Freestyle', time: '6:22.35S', date: '2024-05-10' },
        { event: '25m Backstroke', time: '20.04S', date: '2024-05-10' },
        { event: '50m Backstroke', time: '40.20S', date: '2024-05-10' },
        { event: '100m Backstroke', time: '1:32.65S', date: '2024-05-10' },
        { event: '25m Breaststroke', time: '21.92S', date: '2024-05-10' },
        { event: '50m Breaststroke', time: '45.56S', date: '2024-05-10' },
        { event: '100m Breaststroke', time: '1:50.30S', date: '2024-05-10' },
        { event: '200m Breaststroke', time: '3:46.62S', date: '2024-05-10' },
        { event: '25m Butterfly', time: '20.50S', date: '2024-05-10' },
        { event: '50m Butterfly', time: '36.61S', date: '2024-05-10' },
        { event: '100m Butterfly', time: '1:47.10S', date: '2024-05-10' },
        { event: '100m IM', time: '1:31.90S', date: '2024-05-10' },
        { event: '200m IM', time: '3:21.99S', date: '2024-05-10' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/ivanckassaka',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elsie-letaru',
    name: 'Elsie Letaru',
    age: 11,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elsieletaru',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'eleanor-nakimuli-gabriela',
    name: 'Eleanor Nakimuli GABRIELA',
    age: 11,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '50m Freestyle', time: '33.10S', date: '2024-06-05' },
        { event: '100m Freestyle', time: '1:14.90S', date: '2024-06-05' },
        { event: '200m Freestyle', time: '2:48.40S', date: '2024-06-05' },
        { event: '400m Freestyle', time: '5:55.11S', date: '2024-06-05' },
        { event: '50m Backstroke', time: '38.08S', date: '2024-06-05' },
        { event: '100m Backstroke', time: '1:22.58S', date: '2024-06-05' },
        { event: '200m Backstroke', time: '2:56.73S', date: '2024-06-05' },
        { event: '25m Breaststroke', time: '26.11S', date: '2024-06-05' },
        { event: '50m Breaststroke', time: '45.68S', date: '2024-06-05' },
        { event: '100m Breaststroke', time: '1:43.72S', date: '2024-06-05' },
        { event: '200m Breaststroke', time: '3:38.94S', date: '2024-06-05' },
        { event: '50m Butterfly', time: '38.82S', date: '2024-06-05' },
        { event: '100m Butterfly', time: '1:41.14S', date: '2024-06-05' },
        { event: '200m Butterfly', time: '3:37.98S', date: '2024-06-05' },
        { event: '100m IM', time: '1:27.97S', date: '2024-06-05' },
        { event: '200m IM', time: '3:15.20S', date: '2024-06-05' },
        { event: '400m IM', time: '6:53.48S', date: '2024-06-05' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/eleanornakimuligabriela',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'tyrone-tinkamanyire',
    name: 'Tyrone Tinkamanyire',
    age: 11,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/tyronetinkamanyire',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'sebastian-ssimbwa-luke',
    name: 'Sebastian Ssimbwa Luke',
    age: 11,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '16.56S', date: '2024-07-12' },
        { event: '50m Freestyle', time: '31.41S', date: '2024-07-12' },
        { event: '100m Freestyle', time: '1:14.04L', date: '2024-07-12' },
        { event: '200m Freestyle', time: '2:38.03S', date: '2024-07-12' },
        { event: '400m Freestyle', time: '5:31.46S', date: '2024-07-12' },
        { event: '25m Backstroke', time: '19.28S', date: '2024-07-12' },
        { event: '50m Backstroke', time: '39.59S', date: '2024-07-12' },
        { event: '100m Backstroke', time: '1:31.49L', date: '2024-07-12' },
        { event: '25m Breaststroke', time: '23.81S', date: '2024-07-12' },
        { event: '50m Breaststroke', time: '45.44S', date: '2024-07-12' },
        { event: '100m Breaststroke', time: '1:43.74L', date: '2024-07-12' },
        { event: '200m Breaststroke', time: '3:50.09S', date: '2024-07-12' },
        { event: '25m Butterfly', time: '22.09S', date: '2024-07-12' },
        { event: '50m Butterfly', time: '37.39S', date: '2024-07-12' },
        { event: '100m Butterfly', time: '1:52.63S', date: '2024-07-12' },
        { event: '200m Butterfly', time: '3:28.03S', date: '2024-07-12' },
        { event: '100m IM', time: '1:24.67S', date: '2024-07-12' },
        { event: '200m IM', time: '3:00.49S', date: '2024-07-12' },
        { event: '400m IM', time: '6:38.33S', date: '2024-07-12' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/lukesebastianssimbwa',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'karl-katongole',
    name: 'Karl Katongole',
    age: 12,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '50m Freestyle', time: '37.39S', date: '2024-08-03' },
        { event: '100m Freestyle', time: '1:22.58S', date: '2024-08-03' },
        { event: '400m Freestyle', time: '6:15.32S', date: '2024-08-03' },
        { event: '50m Backstroke', time: '44.15S', date: '2024-08-03' },
        { event: '100m Backstroke', time: '1:37.21S', date: '2024-08-03' },
        { event: '200m Backstroke', time: '3:24.93S', date: '2024-08-03' },
        { event: '25m Breaststroke', time: '33.22S', date: '2024-08-03' },
        { event: '50m Breaststroke', time: '52.01S', date: '2024-08-03' },
        { event: '100m Breaststroke', time: '2:36.47S', date: '2024-08-03' },
        { event: '50m Butterfly', time: '50.81S', date: '2024-08-03' },
        { event: '100m Butterfly', time: '2:01.34S', date: '2024-08-03' },
        { event: '100m IM', time: '1:52.35S', date: '2024-08-03' },
        { event: '200m IM', time: '3:38.61L', date: '2024-08-03' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/karlkatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kristian-mugumya-bwisho',
    name: 'Kristian Mugumya Bwisho',
    age: 12,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A dedicated swimmer who has secured 6 Gold medals and one Bronze medal since starting competitive swimming in February 2023. [22]',
    personalBests: [
        { event: '25m Freestyle', time: '14.81S' },
        { event: '50m Freestyle', time: '28.90S' },
        { event: '100m Freestyle', time: '1:04.48S' },
        { event: '200m Freestyle', time: '2:26.51S' },
        { event: '400m Freestyle', time: '5:39.37L' },
        { event: '25m Backstroke', time: '18.10S' },
        { event: '50m Backstroke', time: '32.99S' },
        { event: '100m Backstroke', time: '1:15.16S' },
        { event: '200m Backstroke', time: '2:47.54S' },
        { event: '25m Breaststroke', time: '19.97S' },
        { event: '50m Breaststroke', time: '36.07S' },
        { event: '100m Breaststroke', time: '1:22.24S' },
        { event: '200m Breaststroke', time: '3:03.78S' },
        { event: '25m Butterfly', time: '16.28S' },
        { event: '50m Butterfly', time: '32.42S' },
        { event: '100m Butterfly', time: '1:20.70S' },
        { event: '200m Butterfly', time: '3:01.68S' },
        { event: '100m IM', time: '1:13.45S' },
        { event: '200m IM', time: '2:48.58L' }
    ],
    galas: [],
    achievements: ['6 Gold medals', '1 Bronze medal'],
    profileUrl: 'https://www.ugandaswimming.com/kristianbwisho',
    joinedDate: '',
    favoriteStroke: '',
    goals: ['Represent Uganda at the highest level of competitive swimming. [22]']
  },
  {
    id: 'jeremiah-ssempijja',
    name: 'Jeremiah Ssempijja',
    age: 12,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '17.56S' },
        { event: '50m Freestyle', time: '33.35S' },
        { event: '100m Freestyle', time: '1:13.89S' },
        { event: '200m Freestyle', time: '2:41.60S' },
        { event: '400m Freestyle', time: '5:45.19S' },
        { event: '25m Backstroke', time: '21.19S' },
        { event: '50m Backstroke', time: '40.10S' },
        { event: '100m Backstroke', time: '1:28.40S' },
        { event: '200m Backstroke', time: '3:13.53S' },
        { event: '25m Breaststroke', time: '20.32S' },
        { event: '50m Breaststroke', time: '39.19S' },
        { event: '100m Breaststroke', time: '1:26.36S' },
        { event: '200m Breaststroke', time: '3:03.72S' },
        { event: '25m Butterfly', time: '21.18S' },
        { event: '50m Butterfly', time: '38.34S' },
        { event: '100m Butterfly', time: '1:27.41S' },
        { event: '200m Butterfly', time: '3:26.40S' },
        { event: '100m IM', time: '1:21.73S' },
        { event: '200m IM', time: '3:00.82L' },
        { event: '400m IM', time: '6:40.60S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/jeremiahssempijja',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'shona-mugisha',
    name: 'Shona Mugisha',
    age: 12,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '28.75S' },
        { event: '50m Freestyle', time: '35.41S' },
        { event: '100m Freestyle', time: '1:26.40S' },
        { event: '200m Freestyle', time: '3:18.37S' },
        { event: '25m Backstroke', time: '31.23S' },
        { event: '50m Backstroke', time: '42.53S' },
        { event: '100m Backstroke', time: '1:39.49S' },
        { event: '200m Backstroke', time: '3:43.54S' },
        { event: '25m Breaststroke', time: '30.59S' },
        { event: '50m Breaststroke', time: '50.38S' },
        { event: '100m Breaststroke', time: '1:50.84S' },
        { event: '25m Butterfly', time: '41.94S' },
        { event: '50m Butterfly', time: '45.25S' },
        { event: '100m IM', time: '1:37.25S' },
        { event: '200m IM', time: '3:42.01S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/shonamugisha',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'victoria-ssaka',
    name: 'Victoria Ssaka',
    age: 12,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '21.37S' },
        { event: '50m Freestyle', time: '31.54S' },
        { event: '100m Freestyle', time: '1:14.35S' },
        { event: '200m Freestyle', time: '2:54.32S' },
        { event: '400m Freestyle', time: '6:22.35S' },
        { event: '25m Backstroke', time: '26.31S' },
        { event: '50m Backstroke', time: '40.20S' },
        { event: '100m Backstroke', time: '1:32.65S' },
        { event: '25m Breaststroke', time: '32.18S' },
        { event: '50m Breaststroke', time: '45.56S' },
        { event: '100m Breaststroke', time: '1:51.45S' },
        { event: '200m Breaststroke', time: '4:03.68S' },
        { event: '25m Butterfly', time: '27.60S' },
        { event: '50m Butterfly', time: '36.61S' },
        { event: '100m IM', time: '1:31.90S' },
        { event: '200m IM', time: '3:21.99S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/victoriassaka',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elijah-shakazulu',
    name: 'Elijah ShakaZulu',
    age: 13,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '22.58S' },
        { event: '50m Freestyle', time: '30.81S' },
        { event: '100m Freestyle', time: '1:10.85S' },
        { event: '200m Freestyle', time: '2:42.62S' },
        { event: '800m Freestyle', time: '12:07.05S' },
        { event: '25m Backstroke', time: '26.87S' },
        { event: '50m Backstroke', time: '38.35S' },
        { event: '100m Backstroke', time: '1:30.32S' },
        { event: '200m Backstroke', time: '2:56.52S' },
        { event: '25m Breaststroke', time: '25.88S' },
        { event: '50m Breaststroke', time: '44.75S' },
        { event: '200m Breaststroke', time: '3:30.31S' },
        { event: '25m Butterfly', time: '22.72S' },
        { event: '50m Butterfly', time: '35.18S' },
        { event: '100m Butterfly', time: '1:21.62S' },
        { event: '200m Butterfly', time: '3:28.61S' },
        { event: '100m IM', time: '1:23.59S' },
        { event: '200m IM', time: '3:05.58S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elijahshakazulu',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'genevieve-mary-murungi',
    name: 'Genevieve Mary Murungi',
    age: 14,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '50m Freestyle', time: '31.54S' },
        { event: '100m Freestyle', time: '1:21.49S' },
        { event: '200m Freestyle', time: '3:04.15S' },
        { event: '50m Backstroke', time: '44.29S' },
        { event: '100m Backstroke', time: '1:43.54S' },
        { event: '200m Backstroke', time: '3:34.07S' },
        { event: '50m Breaststroke', time: '53.21S' },
        { event: '50m Butterfly', time: '48.63S' },
        { event: '200m IM', time: '3:40.95S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/genevievemarymurungi',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elijah-polo',
    name: 'Elijah Polo',
    age: 14,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '25m Freestyle', time: '19.18S' },
        { event: '50m Freestyle', time: '29.41S' },
        { event: '100m Freestyle', time: '1:04.78S' },
        { event: '200m Freestyle', time: '2:22.55S' },
        { event: '400m Freestyle', time: '5:35.01S' },
        { event: '25m Backstroke', time: '21.86S' },
        { event: '50m Backstroke', time: '34.69S' },
        { event: '100m Backstroke', time: '1:15.16S' },
        { event: '25m Breaststroke', time: '21.21S' },
        { event: '50m Breaststroke', time: '37.43S' },
        { event: '100m Breaststroke', time: '1:22.28S' },
        { event: '200m Breaststroke', time: '3:20.18S' },
        { event: '25m Butterfly', time: '20.58S' },
        { event: '50m Butterfly', time: '40.18S' },
        { event: '100m Butterfly', time: '1:39.68S' },
        { event: '100m IM', time: '1:25.75S' },
        { event: '200m IM', time: '3:18.37S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elijahpolo',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'mellanie-manuella-dande',
    name: 'Mellanie Manuella Dande',
    age: 14,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/mellaniemanuelladande',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'solange-katongole',
    name: 'Solange Katongole',
    age: 14,
    squad: 'development',
    imageUrl: '/logo/logo.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '50m Freestyle', time: '36.74S' },
        { event: '100m Freestyle', time: '1:21.78S' },
        { event: '200m Freestyle', time: '3:02.05S' },
        { event: '50m Backstroke', time: '43.09S' },
        { event: '100m Backstroke', time: '1:52.02S' },
        { event: '25m Breaststroke', time: '26.63S' },
        { event: '50m Breaststroke', time: '47.46S' },
        { event: '100m Breaststroke', time: '1:47.49S' },
        { event: '200m Breaststroke', time: '3:56.27S' },
        { event: '50m Butterfly', time: '43.62S' },
        { event: '100m Butterfly', time: '1:42.65S' },
        { event: '100m IM', time: '1:36.04S' },
        { event: '200m IM', time: '3:31.96S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/solangekatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },

  // Performance Squad
  {
    id: 'isaiah-kuc',
    name: 'Isaiah Kuc',
    age: 16,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '25m Freestyle', time: '16.50S' },
        { event: '50m Freestyle', time: '26.02S' },
        { event: '100m Freestyle', time: '55.49S' },
        { event: '200m Freestyle', time: '2:01.83S' },
        { event: '400m Freestyle', time: '4:47.44S' },
        { event: '800m Freestyle', time: '9:32.44S' },
        { event: '25m Backstroke', time: '21.23S' },
        { event: '50m Backstroke', time: '32.42S' },
        { event: '100m Backstroke', time: '1:13.13S' },
        { event: '25m Breaststroke', time: '17.00S' },
        { event: '50m Breaststroke', time: '35.30S' },
        { event: '100m Breaststroke', time: '1:16.58S' },
        { event: '200m Breaststroke', time: '2:41.90S' },
        { event: '25m Butterfly', time: '18.37S' },
        { event: '50m Butterfly', time: '26.74S' },
        { event: '100m Butterfly', time: '1:00.15S' },
        { event: '200m Butterfly', time: '2:19.52S' },
        { event: '100m IM', time: '1:07.59S' },
        { event: '200m IM', time: '2:39.04S' },
        { event: '400m IM', time: '5:28.86S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/isaiahkuc',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kylee-katongole',
    name: 'Kylee Katongole',
    age: 16,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '34.75S' },
        { event: '100m Freestyle', time: '1:20.37S' },
        { event: '200m Freestyle', time: '3:16.65S' },
        { event: '50m Backstroke', time: '45.81S' },
        { event: '25m Breaststroke', time: '23.03S' },
        { event: '50m Breaststroke', time: '46.94S' },
        { event: '100m Breaststroke', time: '1:51.00S' },
        { event: '200m Breaststroke', time: '4:03.30S' },
        { event: '50m Butterfly', time: '38.42S' },
        { event: '100m Butterfly', time: '1:42.98S' },
        { event: '100m IM', time: '1:38.43S' },
        { event: '200m IM', time: '3:30.30S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/kyleekatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'jethro-mugisha',
    name: 'Jethro Mugisha',
    age: 16,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '25m Freestyle', time: '18.01S' },
        { event: '50m Freestyle', time: '28.25S' },
        { event: '100m Freestyle', time: '1:03.80S' },
        { event: '200m Freestyle', time: '2:53.06S' },
        { event: '400m Freestyle', time: '6:26.65S' },
        { event: '25m Backstroke', time: '20.67S' },
        { event: '50m Backstroke', time: '33.65S' },
        { event: '100m Backstroke', time: '1:28.57S' },
        { event: '200m Backstroke', time: '3:19.88S' },
        { event: '25m Breaststroke', time: '25.32S' },
        { event: '50m Breaststroke', time: '36.19S' },
        { event: '100m Breaststroke', time: '1:23.81S' },
        { event: '200m Breaststroke', time: '3:56.04S' },
        { event: '25m Butterfly', time: '19.87S' },
        { event: '50m Butterfly', time: '31.29S' },
        { event: '100m Butterfly', time: '1:27.26S' },
        { event: '100m IM', time: '1:18.77S' },
        { event: '200m IM', time: '2:49.60S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/jethromugisha',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'raya-inell-ba',
    name: 'Raya Inell Ba',
    age: 16,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '25m Freestyle', time: '18.68S' },
        { event: '50m Freestyle', time: '27.92S' },
        { event: '100m Freestyle', time: '1:05.49S' },
        { event: '200m Freestyle', time: '2:35.18S' },
        { event: '400m Freestyle', time: '6:07.95S' },
        { event: '25m Backstroke', time: '21.60S' },
        { event: '50m Backstroke', time: '34.03S' },
        { event: '100m Backstroke', time: '1:25.74S' },
        { event: '200m Backstroke', time: '3:06.19S' },
        { event: '25m Breaststroke', time: '23.27S' },
        { event: '50m Breaststroke', time: '35.80S' },
        { event: '100m Breaststroke', time: '1:20.88S' },
        { event: '200m Breaststroke', time: '3:32.35S' },
        { event: '25m Butterfly', time: '19.38S' },
        { event: '50m Butterfly', time: '30.45S' },
        { event: '100m Butterfly', time: '1:11.29S' },
        { event: '100m IM', time: '1:25.15S' },
        { event: '200m IM', time: '2:58.78S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/rayainellba',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kayla-elisha-arinda',
    name: 'Kayla Elisha Arinda',
    age: 17,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '32.03S' },
        { event: '100m Freestyle', time: '1:12.54S' },
        { event: '200m Freestyle', time: '2:40.26S' },
        { event: '400m Freestyle', time: '5:56.09S' },
        { event: '800m Freestyle', time: '12:10.93S' },
        { event: '50m Backstroke', time: '38.81S' },
        { event: '100m Backstroke', time: '1:26.47S' },
        { event: '200m Backstroke', time: '3:03.72S' },
        { event: '50m Breaststroke', time: '43.73S' },
        { event: '100m Breaststroke', time: '1:37.42S' },
        { event: '200m Breaststroke', time: '3:32.80S' },
        { event: '50m Butterfly', time: '36.30S' },
        { event: '100m Butterfly', time: '1:24.52S' },
        { event: '200m Butterfly', time: '3:10.21S' },
        { event: '100m IM', time: '1:23.82S' },
        { event: '200m IM', time: '3:03.07S' },
        { event: '400m IM', time: '6:34.19S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/kaylaelishaarinda',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'shane-katongole',
    name: 'Shane Katongole',
    age: 18,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '30.05S' },
        { event: '100m Freestyle', time: '1:09.78S' },
        { event: '200m Freestyle', time: '2:43.86S' },
        { event: '50m Backstroke', time: '42.46S' },
        { event: '25m Breaststroke', time: '19.71S' },
        { event: '50m Breaststroke', time: '40.02S' },
        { event: '100m Breaststroke', time: '1:31.71S' },
        { event: '200m Breaststroke', time: '3:34.34S' },
        { event: '50m Butterfly', time: '32.29S' },
        { event: '100m Butterfly', time: '1:29.81S' },
        { event: '100m IM', time: '1:29.43S' },
        { event: '200m IM', time: '3:18.15S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/shanekatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'sulea-namubiru',
    name: 'Sulea Namubiru',
    age: 19,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/suleanamubiru',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'karla-mugisha',
    name: 'Karla Mugisha',
    age: 19,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '28.98S' },
        { event: '100m Freestyle', time: '1:05.90S' },
        { event: '200m Freestyle', time: '2:32.18S' },
        { event: '400m Freestyle', time: '6:02.12S' },
        { event: '50m Backstroke', time: '34.28S' },
        { event: '100m Backstroke', time: '1:18.99S' },
        { event: '200m Backstroke', time: '3:03.05S' },
        { event: '50m Breaststroke', time: '36.94S' },
        { event: '100m Breaststroke', time: '1:23.31S' },
        { event: '200m Breaststroke', time: '3:17.07S' },
        { event: '50m Butterfly', time: '32.85S' },
        { event: '100m Butterfly', time: '1:18.18S' },
        { event: '100m IM', time: '1:16.04S' },
        { event: '200m IM', time: '2:54.23S' },
        { event: '400m IM', time: '6:31.25S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/karlamugisha',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'malcolm-okecho',
    name: 'Malcolm Okecho',
    age: 19,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '32.96S' },
        { event: '50m Backstroke', time: '42.94S' },
        { event: '50m Breaststroke', time: '42.78S' },
        { event: '50m Butterfly', time: '44.72S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/malcolmokecho',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'larry-graig-feni',
    name: 'Larry Graig Feni',
    age: 19,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '24.87S' },
        { event: '100m Freestyle', time: '59.00S' },
        { event: '200m Freestyle', time: '3:16.33S' },
        { event: '50m Backstroke', time: '29.36S' },
        { event: '25m Breaststroke', time: '14.56S' },
        { event: '50m Breaststroke', time: '30.30S' },
        { event: '100m Breaststroke', time: '1:08.29S' },
        { event: '50m Butterfly', time: '27.25S' },
        { event: '100m IM', time: '1:05.34S' },
        { event: '200m IM', time: '2:30.17S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/larrygraigfeni',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'esther-atto',
    name: 'Esther Atto',
    age: 19,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '30.33S' },
        { event: '100m Freestyle', time: '1:10.36S' },
        { event: '200m Freestyle', time: '3:13.60S' },
        { event: '50m Backstroke', time: '39.59S' },
        { event: '100m Backstroke', time: '1:38.28S' },
        { event: '50m Breaststroke', time: '41.03S' },
        { event: '100m Breaststroke', time: '1:33.75S' },
        { event: '50m Butterfly', time: '33.85S' },
        { event: '100m Butterfly', time: '1:26.24S' },
        { event: '100m IM', time: '1:27.57S' },
        { event: '200m IM', time: '3:30.80S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/estheratto',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'namanya-ampaire',
    name: 'Namanya Ampaire',
    age: 21,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '25.94S' },
        { event: '100m Freestyle', time: '1:01.24S' },
        { event: '200m Freestyle', time: '2:13.86S' },
        { event: '400m Freestyle', time: '5:13.61S' },
        { event: '800m Freestyle', time: '10:50.81S' },
        { event: '50m Backstroke', time: '31.78S' },
        { event: '100m Backstroke', time: '1:09.98S' },
        { event: '200m Backstroke', time: '2:50.08S' },
        { event: '50m Breaststroke', time: '30.99S' },
        { event: '100m Breaststroke', time: '1:08.58S' },
        { event: '200m Breaststroke', time: '2:33.02S' },
        { event: '50m Butterfly', time: '27.29S' },
        { event: '100m Butterfly', time: '1:15.20S' },
        { event: '200m Butterfly', time: '2:56.77S' },
        { event: '100m IM', time: '1:05.63S' },
        { event: '200m IM', time: '2:27.29S' },
        { event: '400m IM', time: '5:50.82S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/ampairenamanya',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'jagwe-eliab',
    name: 'Jagwe Eliab',
    age: 21,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/jagweeliab',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'trevor-kimuli-john',
    name: 'Trevor Kimuli John',
    age: 24,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '25.11S' },
        { event: '100m Freestyle', time: '1:00.20L' },
        { event: '200m Freestyle', time: '2:35.43S' },
        { event: '50m Backstroke', time: '29.75S' },
        { event: '100m Backstroke', time: '1:11.24S' },
        { event: '25m Breaststroke', time: '14.53S' },
        { event: '50m Breaststroke', time: '30.46S' },
        { event: '100m Breaststroke', time: '1:10.65S' },
        { event: '200m Breaststroke', time: '2:54.62S' },
        { event: '50m Butterfly', time: '26.85S' },
        { event: '100m Butterfly', time: '1:13.74S' },
        { event: '100m IM', time: '1:10.56S' },
        { event: '200m IM', time: '2:40.86S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/trevorkimulijohn',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
      "id": "ariyo-ahumuza",
      "name": "Ariyo Ahumuza",
      "age": 23,
      "squad": "performance",
      "imageUrl": "/logo/logo.jpg",
      "bio": "A talented swimmer in the performance squad, consistently achieving personal bests.",
      "personalBests": [
          { "event": "50m Freestyle", "time": "26.70S" },
          { "event": "100m Freestyle", "time": "1:22.63S" },
          { "event": "200m Freestyle", "time": "2:31.92S" },
          { "event": "50m Backstroke", "time": "38.14S" },
          { "event": "100m Backstroke", "time": "1:13.20S" },
          { "event": "50m Breaststroke", "time": "33.09S" },
          { "event": "100m Breaststroke", "time": "1:16.99S" },
          { "event": "200m Breaststroke", "time": "2:51.23S" },
          { "event": "50m Butterfly", "time": "30.06S" },
          { "event": "100m Butterfly", "time": "1:09.59S" },
          { "event": "100m IM", "time": "1:18.03S" },
          { "event": "200m IM", "time": "2:38.96S" }
      ],
      "galas": [],
      "achievements": [],
      "profileUrl": "https://www.ugandaswimming.com/ahumuzaariyo",
      "joinedDate": "",
      "favoriteStroke": "",
      "goals": []
  },
  {
    id: 'jacob-mugisha',
    name: 'Jacob Mugisha',
    age: 25,
    squad: 'performance',
    imageUrl: '/logo/logo.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '26.48S' },
        { event: '100m Freestyle', time: '58.35S' },
        { event: '50m Butterfly', time: '28.63S' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/mjjacob',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  }
];

export const UPCOMING_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Regional Swimming Championships',
    date: '2025-01-25',
    time: '9:00 AM',
    venue: 'Kampala Aquatic Center',
    description: 'Annual regional championships featuring swimmers from across East Africa.',
    type: 'competition',
    registrationOpen: true,
    capacity: 150,
    registered: 89,
    imageUrl: '/hero-images/dubai_1.jpg'
  },
  {
    id: '2',
    title: 'Technique Workshop: Butterfly Stroke',
    date: '2025-02-08',
    time: '2:00 PM',
    venue: 'Silverfin Academy Pool',
    description: 'Master the butterfly stroke with our expert coaches in this intensive workshop.',
    type: 'workshop',
    registrationOpen: true,
    capacity: 25,
    registered: 18,
    imageUrl: '/logo/logo.jpg'
  },
  {
    id: '3',
    title: 'Youth Development Meet',
    date: '2025-02-15',
    time: '10:00 AM',
    venue: 'Entebbe Sports Complex',
    description: 'Competitive meet focused on developing young swimmers aged 8-16.',
    type: 'competition',
    registrationOpen: true,
    capacity: 100,
    registered: 67,
    imageUrl: '/logo/logo.jpg'
  },
  {
    id: '4',
    title: 'Silverfin Swimming Gala 2025',
    date: '2025-03-15',
    time: '8:00 AM',
    venue: 'Kampala Aquatic Center',
    description: 'Our flagship annual event featuring five prestigious swimming events.',
    type: 'gala',
    registrationOpen: false,
    capacity: 200,
    registered: 156,
    imageUrl: '/hero-images/pentathlon_1.jpg'
  }
];

export const PAST_EVENTS: Event[] = [
  {
    id: 'past-1',
    title: 'Silverfin Swimming Gala 2024',
    date: '2024-03-16',
    time: '8:00 AM',
    venue: 'Kampala Aquatic Center',
    description: 'Our flagship annual swimming gala featuring top swimmers from across East Africa.',
    type: 'gala',
    registrationOpen: false,
    participants: 187,
    imageUrl: '/hero-images/nationals_1.jpg',
    highlights: [
      '3 new pool records set',
      'Largest participation in academy history',
      'International swimmers from 5 countries',
      'Live streaming reached 10,000 viewers'
    ],
    results: [
      { category: '50m Freestyle (Men)', winner: 'John Mukasa', time: '22.34' },
      { category: '100m Butterfly (Women)', winner: 'Sarah Nankabirwa', time: '1:02.45' },
      { category: '200m Backstroke (Men)', winner: 'David Okello', time: '2:08.12' }
    ]
  },
  {
    id: 'past-2',
    title: 'East African Championships',
    date: '2024-11-22',
    time: '9:00 AM',
    venue: 'Nairobi Aquatic Complex',
    description: 'Regional championship bringing together the best swimmers from East Africa.',
    type: 'competition',
    registrationOpen: false,
    participants: 156,
    imageUrl: '/hero-images/pentathlon_2.jpg',
    highlights: [
      'Silverfin swimmers won 12 medals',
      '4 swimmers qualified for nationals',
      'Team finished 2nd overall',
      'Outstanding team performance'
    ],
    results: [
      { category: '100m Freestyle (Women)', winner: 'Grace Namatovu', time: '56.78' },
      { category: '200m Medley (Men)', winner: 'Samuel Kiprotich', time: '2:15.34' },
      { category: '4x100m Relay (Mixed)', winner: 'Silverfin Team A', time: '3:45.67' }
    ]
  },
  {
    id: 'past-3',
    title: 'Youth Development Championships',
    date: '2024-09-14',
    time: '10:00 AM',
    venue: 'Entebbe Sports Complex',
    description: 'Championship focused on developing young swimming talent aged 8-16.',
    type: 'competition',
    registrationOpen: false,
    participants: 89,
    imageUrl: '/logo/logo.jpg',
    highlights: [
      '45 personal best times achieved',
      '8 new age group records',
      'Outstanding youth development',
      'Fun and educational experience'
    ]
  }
];

export const CALENDAR_EVENTS = [
  { id: '1', title: 'Regional Championships', date: '2025-01-25', type: 'competition' as const },
  { id: '2', title: 'Butterfly Workshop', date: '2025-02-08', type: 'workshop' as const },
  { id: '3', title: 'Youth Development Meet', date: '2025-02-15', type: 'competition' as const },
  { id: '4', title: 'Advanced Training', date: '2025-02-22', type: 'training' as const },
  { id: '5', title: 'Silverfin Gala', date: '2025-03-15', type: 'gala' as const },
  { id: '6', title: 'Inter-school Championships', date: '2025-03-29', type: 'competition' as const },
  { id: '7', title: 'Freestyle Technique', date: '2025-04-05', type: 'workshop' as const },
  { id: '8', title: 'National Qualifiers', date: '2025-04-19', type: 'competition' as const },
];