import { ContactInfo, SocialMedia, Stat, Program, Coach, Facility, Swimmer } from '../types';

export const CONTACT_INFO: ContactInfo = {
  phone: '+256 709 711 797',
  email: 'silverfinacademy@gmail.com',
  address: 'Hill Preparatory School, Naguru, Kampala'
};

export const SOCIAL_MEDIA: SocialMedia = {
  instagram: 'https://instagram.com/silverfinacademy',
  facebook: 'https://facebook.com/silverfinacademy',
  youtube: 'https://youtube.com/silverfinacademy'
};

export const CLUB_STATS: Stat[] = [
  { value: '150+', label: 'Active Members' },
  { value: '92', label: 'Medals Won' },
  { value: '14', label: 'Coaches & Staff' },
  { value: '6', label: 'Training Squads' }
];

export const PROGRAMS: Program[] = [
  {
    id: 'learn-to-swim',
    title: 'Learn to Swim',
    description: 'Water confidence, safety, and foundational technique for beginners.',
    meta: 'Ages 4–10 • Weekdays',
    ageGroup: '4-10',
    price: 150000,
    duration: '4 weeks'
  },
  {
    id: 'development-squads',
    title: 'Development Squads',
    description: 'Skill refinement and aerobic base with fun, progressive sets.',
    meta: 'Ages 9–14 • 4–6 sessions/week',
    ageGroup: '9-14',
    price: 300000,
    duration: 'Monthly'
  },
  {
    id: 'performance-senior',
    title: 'Performance / Senior',
    description: 'High‑performance training targeting national and international meets.',
    meta: 'Ages 13+ • 7–9 sessions/week',
    ageGroup: '13+',
    price: 500000,
    duration: 'Monthly'
  }
];

export const COACHES: Coach[] = [
  {
    id: 'ezra-kakali',
    name: 'Ezra Kakali',
    title: 'Head Coach',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'Former national team swimmer with 15+ years coaching experience leading Silverfin to regional excellence. Ezra represented Uganda at the Commonwealth Games and African Championships before transitioning to coaching. His technical expertise and leadership have transformed countless swimmers into champions.',
    quote: "Excellence is not a destination, it's a journey. Every stroke, every training session, every competition is an opportunity to become better than you were yesterday.",
    background: 'Swimming Career: Competed internationally for Uganda (2005-2012)\nCoaching Experience: 15+ years developing athletes from beginner to elite level\nEducation: Sports Science degree, University of Makerere\nAchievements: Led 50+ swimmers to national championships, developed 12 African Championship medalists',
    certifications: [
      'Level 4 Swimming Coach (Swimming Federation)',
      'Strength & Conditioning Specialist (NSCA)',
      'Water Safety Instructor (Red Cross)',
      'Mental Performance Coach',
      'Technical Official Level 3',
      'First Aid/CPR Certified'
    ]
  },
  {
    id: 'vincent-kabira',
    name: 'Vincent Kabira',
    title: 'Assistant Head Coach',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'Specialist in competitive swimming development with expertise in stroke technique and race strategy. Vincent focuses on developing proper fundamentals and building competitive confidence in swimmers of all levels.',
    quote: "Technique is the foundation of speed. Perfect practice makes perfect performance, and every swimmer has the potential to achieve greatness with the right guidance.",
    background: 'Swimming Career: Former national age-group record holder\nCoaching Experience: 8+ years specializing in technique development\nEducation: Physical Education degree, Kyambogo University\nSpecialization: Stroke biomechanics and race preparation',
    certifications: [
      'Level 3 Swimming Coach',
      'Technical Official Level 2',
      'Child Protection Certified',
      'Video Analysis Specialist',
      'Age Group Development Coach',
      'First Aid/CPR Certified'
    ]
  },
  {
    id: 'mugisha-jacob',
    name: 'Mugisha Jacob',
    title: 'Learn to Swim Coach (Adults)',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'Dedicated adult swimming instructor with a passion for helping beginners overcome water fears and develop confidence in the water. Jacob specializes in working with adult learners who are taking up swimming later in life.',
    background: 'Teaching Experience: 6+ years specializing in adult education\nEducation: Certificate in Adult Education, YMCA\nSpecialization: Water confidence and fear management\nSuccess Rate: 95% of students achieve basic swimming competency',
    certifications: [
      'Adult Swimming Instructor (Level 2)',
      'Water Safety Instructor',
      'First Aid/CPR Certified',
      'Aquatic Therapy Assistant',
      'Adult Education Certificate'
    ]
  },
  {
    id: 'nancy-akukwatswe',
    name: 'Nancy Akukwatswe',
    title: 'Learn to Swim Coach (Children)',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'Patient and encouraging instructor specializing in foundational swimming skills for children aged 4-12. Nancy creates a fun, safe environment where young swimmers can develop both skills and confidence.',
    background: 'Teaching Experience: 7+ years in pediatric aquatic education\nEducation: Early Childhood Development Certificate\nSpecialization: Child psychology and motor skill development\nAchievements: Taught over 500 children to swim safely',
    certifications: [
      'Swimming Instructor Level 2 (Children)',
      'Child Development Specialist',
      'Water Confidence Instructor',
      'Pediatric First Aid/CPR',
      'Safeguarding Children Certificate'
    ]
  },
];

export const FACILITIES: Facility[] = [
  {
    name: '8‑lane 25m pool',
    description: 'Olympic standard training pool with electronic timing',
    features: ['Electronic timing', 'Lane ropes', 'Starting blocks']
  },
  {
    name: 'Strength & Conditioning space',
    description: 'Fully equipped gym for dryland training',
    features: ['Free weights', 'Resistance machines', 'Plyometric equipment']
  },
  {
    name: 'Video analysis',
    description: 'State-of-the-art stroke analysis technology',
    features: ['Underwater cameras', 'Motion analysis software', 'Tablet review stations']
  }
];

export const NAV_ITEMS = [
  { id: 'about', label: 'About' },
  { id: 'stats', label: 'Statistics' },
  { id: 'programs', label: 'Programs' },
  { id: 'news', label: 'News' },
  { id: 'gallery', label: 'Gallery' },
  { id: 'contact', label: 'Contact' }
];

export const SWIMMERS: Swimmer[] = [
  // Learn to Swim Squad
  {
    id: 'jeremiah-bwogi-kisawuzi',
    name: 'Jeremiah Bwogi Kisawuzi',
    age: 4,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'rebecca-namiiro',
    name: 'Rebecca Namiiro',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'israel-kanyike',
    name: 'Israel Kanyike',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'gabriel-mwesigwa-james-marie',
    name: 'Gabriel Mwesigwa James-Marie',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'jonatha-bwogi-nabukeera',
    name: 'Jonatha Bwogi Nabukeera',
    age: 5,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'aimie-imora',
    name: 'Aimie Imora',
    age: 6,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'christian-okecho-owori',
    name: 'Christian Okecho Owori',
    age: 6,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'roman-byaruhanga-emanzi',
    name: 'Roman Byaruhanga Emanzi',
    age: 6,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kimuli-enzo-israel',
    name: 'Kimuli Enzo Israel',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kwikiriza-wilma',
    name: 'Kwikiriza Wilma',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'lucas-mugisha',
    name: 'Lucas Mugisha',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'dorothy-nakazi',
    name: 'Dorothy Nakazi',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A young and enthusiastic swimmer, just starting her journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kisakye-mugwanya-gabriella-shalom',
    name: 'Kisakye Mugwanya Gabriella Shalom',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'abisha-abowe',
    name: 'Abisha Abowe',
    age: 7,
    squad: 'learn-to-swim',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A young and enthusiastic swimmer, just starting his journey in the water.',
    personalBests: [],
    galas: [],
    achievements: [],
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },

  // Development Squad
  {
    id: 'nkoola-janine-jolie',
    name: 'Nkoola Janine Jolie',
    age: 8,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/nkoolajaninejolie',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'lionel-abitegeka-edwards',
    name: 'Lionel Abitegeka Edwards',
    age: 8,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/lionelabitegekaedwards',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'tendo-matthew-ssaka',
    name: 'Tendo Matthew Ssaka',
    age: 8,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/tendomatthewssaka',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kanyike-kirabo-elnathan',
    name: 'Kanyike Kirabo Elnathan',
    age: 8,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/kanyikekiraboelnathan',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'bena-nkundwa-ahumuza',
    name: 'Bena Nkundwa Ahumuza',
    age: 8,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/benankundwaahumuza',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elsa-victory-dande',
    name: 'Elsa Victory Dande',
    age: 9,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elsavictorydande',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'gianna-mary-musiimenta',
    name: 'Gianna Mary Musiimenta',
    age: 9,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '50m Freestyle', time: '47.55', date: '', venue: '' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/giannamarymusiimenta',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'diarah-sama',
    name: 'Diarah Sama',
    age: 10,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/diarahsama',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'ivancka-ssaka',
    name: 'Ivancka Ssaka',
    age: 10,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/ivanckassaka',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elsie-letaru',
    name: 'Elsie Letaru',
    age: 11,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elsieletaru',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'eleanor-nakimuli-gabriela',
    name: 'Eleanor Nakimuli GABRIELA',
    age: 11,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/eleanornakimuligabriela',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'tyrone-tinkamanyire',
    name: 'Tyrone Tinkamanyire',
    age: 11,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/tyronetinkamanyire',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'sebastian-ssimbwa-luke',
    name: 'Sebastian Ssimbwa Luke',
    age: 11,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [
        { event: '50m Backstroke', time: '41.02', date: '', venue: '' },
        { event: '25m Breaststroke', time: '23.81', date: '', venue: '' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/lukesebastianssimbwa',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'karl-katongole',
    name: 'Karl Katongole',
    age: 12,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/karlkatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kristian-mugumya-bwisho',
    name: 'Kristian Mugumya Bwisho',
    age: 12,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A dedicated swimmer who has secured 6 Gold medals and one Bronze medal since starting competitive swimming in February 2023. [22]',
    personalBests: [],
    galas: [],
    achievements: ['6 Gold medals', '1 Bronze medal'],
    profileUrl: 'https://www.ugandaswimming.com/kristianbwisho',
    joinedDate: '',
    favoriteStroke: '',
    goals: ['Represent Uganda at the highest level of competitive swimming. [22]']
  },
  {
    id: 'jeremiah-ssempijja',
    name: 'Jeremiah Ssempijja',
    age: 12,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/jeremiahssempijja',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'shona-mugisha',
    name: 'Shona Mugisha',
    age: 12,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/shonamugisha',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'victoria-ssaka',
    name: 'Victoria Ssaka',
    age: 12,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/victoriassaka',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elijah-shakazulu',
    name: 'Elijah ShakaZulu',
    age: 13,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elijahshakazulu',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'genevieve-mary-murungi',
    name: 'Genevieve Mary Murungi',
    age: 14,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/genevievemarymurungi',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'elijah-polo',
    name: 'Elijah Polo',
    age: 14,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/elijahpolo',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'mellanie-manuella-dande',
    name: 'Mellanie Manuella Dande',
    age: 14,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/mellaniemanuelladande',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'solange-katongole',
    name: 'Solange Katongole',
    age: 14,
    squad: 'development',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A promising swimmer in the development squad, showing great potential.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/solangekatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },

  // Performance Squad
  {
    id: 'isaiah-kuc',
    name: 'Isaiah Kuc',
    age: 16,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '800m Freestyle', time: '09:21.70', date: '', venue: '17th Tanzania National' },
        { event: '50m Butterfly', time: '26.16', date: '', venue: 'NTSAA Secondary Swimming' },
        { event: '50m Freestyle', time: '25.65', date: '', venue: 'Arusha International' },
        { event: '200m IM', time: '02:17.89', date: '', venue: '17th Tanzania National' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/isaiahkuc',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kylee-katongole',
    name: 'Kylee Katongole',
    age: 16,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/kyleekatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'jethro-mugisha',
    name: 'Jethro Mugisha',
    age: 16,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/jethromugisha',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'raya-inell-ba',
    name: 'Raya Inell Ba',
    age: 16,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Freestyle', time: '29.85', date: '2024-06-27', venue: '' },
        { event: '50m Breaststroke', time: '38.48', date: '2024-06-27', venue: '' },
        { event: '50m Butterfly', time: '33.09', date: '2024-06-27', venue: '' },
        { event: '100m Breaststroke', time: '01:27.68', date: '2024-06-27', venue: '' },
        { event: '100m Freestyle', time: '01:08.60', date: '2024-06-27', venue: '' },
        { event: '50m Backstroke', time: '37.52', date: '2024-06-27', venue: '' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/rayainellba',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'kayla-elisha-arinda',
    name: 'Kayla Elisha Arinda',
    age: 17,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/kaylaelishaarinda',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'shane-katongole',
    name: 'Shane Katongole',
    age: 18,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/shanekatongole',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'sulea-namubiru',
    name: 'Sulea Namubiru',
    age: 19,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/suleanamubiru',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'karla-mugisha',
    name: 'Karla Mugisha',
    age: 19,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/karlamugisha',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'malcolm-okecho',
    name: 'Malcolm Okecho',
    age: 19,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/malcolmokecho',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'larry-graig-feni',
    name: 'Larry Graig Feni',
    age: 19,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/larrygraigfeni',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'esther-atto',
    name: 'Esther Atto',
    age: 19,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/estheratto',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'namanya-ampaire',
    name: 'Namanya Ampaire',
    age: 21,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_1.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/ampairenamanya',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'jagwe-eliab',
    name: 'Jagwe Eliab',
    age: 21,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_2.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/jagweeliab',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'trevor-kimuli-john',
    name: 'Trevor Kimuli John',
    age: 24,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_3.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/trevorkimulijohn',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  },
  {
    id: 'jacob-mugisha',
    name: 'Jacob Mugisha',
    age: 25,
    squad: 'performance',
    imageUrl: '/hero-images/swimmer_4.jpg',
    bio: 'A talented swimmer in the performance squad, consistently achieving personal bests.',
    personalBests: [
        { event: '50m Butterfly', time: '26.18', date: '', venue: '' }
    ],
    galas: [],
    achievements: [],
    profileUrl: 'https://www.ugandaswimming.com/mjjacob',
    joinedDate: '',
    favoriteStroke: '',
    goals: []
  }
];